name: Release

on:
    push:
        branches:
            - main

jobs:
    release:
        strategy:
            fail-fast: true
            matrix:
                platform: [ubuntu-latest]
        runs-on: ${{ matrix.platform }}

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4.2.0
            -   name: Install Linux-Dependencies
                run: sudo apt update && sudo apt install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
            -   name: Install Rust
                uses: dtolnay/rust-toolchain@stable
            -   name: Install NodeJS
                uses: actions/setup-node@v4.0.4
                with:
                    node-version: 18
            -   name: Install Project-Dependencies
                run: npm install
            -   name: Build Project
                run: npm run build
            -   name: Publish Release Artifacts
                uses: actions/upload-artifact@v4.4.0
                with:
                    name: linux
                    path: /home/runner/work/tauri-test-v2/tauri-test-v2/src-tauri/target/release/app
