name: Release

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4.2.0
    release-windows:
        needs: test
        strategy:
            fail-fast: true
            matrix:
                settings:
                    -   host: windows-latest
                        target: x86_64-pc-windows-msvc
        runs-on: ${{ matrix.settings.host }}
    
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4.2.0
            -   name: Install Rust
                uses: dtolnay/rust-toolchain@stable
            -   name: Install NodeJS
                uses: actions/setup-node@v4.0.4
                with:
                    node-version: 18
            -   name: Install Project-Dependencies
                run: npm install
            -   name: Build Project
                run: npm run build
            -   name: Publish Release Artifacts
                uses: actions/upload-artifact@v4.4.0
                with:
                    name: windows-2
                    path: D:\a\tauri-test-v2\tauri-test-v2\src-tauri\target\release\app.exe
    release-linux:
        needs: test
        strategy:
            fail-fast: true
            matrix:
                settings:
                    -   host: ubuntu-latest
                        target: x86_64-unknown-linux-gnu
        runs-on: ${{ matrix.settings.host }}

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4.2.0
            -   name: Install Linux-Dependencies
                run: sudo apt update && sudo apt install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
            -   name: Install Rust
                uses: dtolnay/rust-toolchain@stable
            -   name: Install NodeJS
                uses: actions/setup-node@v4.0.4
                with:
                    node-version: 18
            -   name: Install Project-Dependencies
                run: npm install
            -   name: Build Project
                run: npm run build
            -   name: Publish Release Artifacts
                uses: actions/upload-artifact@v4.4.0
                with:
                    name: linux
                    path: /home/runner/work/tauri-test-v2/tauri-test-v2/src-tauri/target/release/app
    publish:
        needs: [release-windows, release-linux]
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4.2.0
